// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaTech.TerraTech.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace NovaTech.TerraTech.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005012206_FieldBoundary")]
    partial class FieldBoundary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NovaTech.TerraTech.Platform.AnalyticsManagement.Domain.Model.Aggregates.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_reports");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.CommercialManagement.Domain.Model.Aggregates.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSubscription")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_subscription");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int")
                        .HasColumnName("payment_method");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_name");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_orders");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("i_x_orders_profile_id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.CommercialManagement.Domain.Model.Aggregates.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_products");

                    b.ToTable("products");
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.CommunityManagement.Domain.Model.Aggregates.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AuthorProfileId")
                        .HasColumnType("int")
                        .HasColumnName("author_profile_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("TargetProfileId")
                        .HasColumnType("int")
                        .HasColumnName("target_profile_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_comments");

                    b.HasIndex("AuthorProfileId")
                        .HasDatabaseName("i_x_comments_author_profile_id");

                    b.HasIndex("TargetProfileId")
                        .HasDatabaseName("i_x_comments_target_profile_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.CommunityManagement.Domain.Model.Aggregates.CommunityProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("VisibilityStatus")
                        .HasColumnType("int")
                        .HasColumnName("visibility_status");

                    b.HasKey("Id")
                        .HasName("p_k_community_profiles");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("i_x_community_profiles_profile_id");

                    b.ToTable("community_profiles", (string)null);
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.Aggregates.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("SensorCode")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("sensor_code");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_devices");

                    b.HasIndex("SensorCode")
                        .IsUnique()
                        .HasDatabaseName("i_x_devices_sensor_code");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.Aggregates.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Boundary")
                        .HasColumnType("longtext")
                        .HasColumnName("boundary");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CropName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("crop_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_fields");

                    b.ToTable("fields");
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.Aggregates.SensorCatalogItem", b =>
                {
                    b.Property<string>("SensorCode")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("sensor_code");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_demo");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("mac_address");

                    b.HasKey("SensorCode")
                        .HasName("p_k_sensor_catalog_items");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("i_x_sensor_catalog_items_mac_address");

                    b.ToTable("sensor_catalog_items");
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.Aggregates.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<double>("MoisturePercent")
                        .HasColumnType("double")
                        .HasColumnName("moisture_percent");

                    b.Property<double>("NitrogenPpm")
                        .HasColumnType("double")
                        .HasColumnName("nitrogen_ppm");

                    b.Property<double>("PhosphorusPpm")
                        .HasColumnType("double")
                        .HasColumnName("phosphorus_ppm");

                    b.Property<double>("PotassiumPpm")
                        .HasColumnType("double")
                        .HasColumnName("potassium_ppm");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<double>("SoilTemperatureC")
                        .HasColumnType("double")
                        .HasColumnName("soil_temperature_c");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("p_k_sensor_readings");

                    b.HasIndex("DeviceId", "RecordedAt")
                        .IsUnique()
                        .HasDatabaseName("i_x_sensor_readings_device_id_recorded_at");

                    b.ToTable("sensor_readings");
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.NotificationManagement.Domain.Model.Aggregates.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAlert")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_alert");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("message");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("i_x_notifications_profile_id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.ProfileManagement.Domain.Model.Aggregates.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("location");

                    b.Property<double?>("SizeM2")
                        .HasColumnType("double")
                        .HasColumnName("size_m2");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_profiles_user_id");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.StockManagement.Domain.Model.Aggregates.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("int")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("stock_quantity");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("WarehouseLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("warehouse_location");

                    b.HasKey("Id")
                        .HasName("p_k_inventories");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("i_x_inventories_owner_user_id");

                    b.ToTable("inventories");
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.AnalyticsManagement.Domain.Model.Aggregates.Report", b =>
                {
                    b.OwnsOne("NovaTech.TerraTech.Platform.AnalyticsManagement.Domain.Model.ValueObjects.DeviceId", "DeviceId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("device_id");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.HasIndex("Value")
                                .HasDatabaseName("i_x_reports_device_id");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");

                            b1.HasOne("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.Aggregates.Device", null)
                                .WithMany()
                                .HasForeignKey("Value")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("f_k_reports__device_device_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.AnalyticsManagement.Domain.Model.ValueObjects.GeneratedAt", "GeneratedAt", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("Value")
                                .HasColumnType("datetime")
                                .HasColumnName("generated_at");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.AnalyticsManagement.Domain.Model.ValueObjects.MeanValue", "MeanValue", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<double>("Value")
                                .HasColumnType("double")
                                .HasColumnName("mean_value");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.AnalyticsManagement.Domain.Model.ValueObjects.StandardDeviation", "StandardDeviation", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<double>("Value")
                                .HasColumnType("double")
                                .HasColumnName("standard_deviation");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.AnalyticsManagement.Domain.Model.ValueObjects.TechnicalInterpretation", "TechnicalInterpretation", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("technical_interpretation");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.AnalyticsManagement.Domain.Model.ValueObjects.Variance", "Variance", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<double>("Value")
                                .HasColumnType("double")
                                .HasColumnName("variance");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.Navigation("DeviceId")
                        .IsRequired();

                    b.Navigation("GeneratedAt")
                        .IsRequired();

                    b.Navigation("MeanValue")
                        .IsRequired();

                    b.Navigation("StandardDeviation")
                        .IsRequired();

                    b.Navigation("TechnicalInterpretation")
                        .IsRequired();

                    b.Navigation("Variance")
                        .IsRequired();
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.CommercialManagement.Domain.Model.Aggregates.Order", b =>
                {
                    b.HasOne("NovaTech.TerraTech.Platform.ProfileManagement.Domain.Model.Aggregates.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_orders__profile_profile_id");
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.CommunityManagement.Domain.Model.Aggregates.Comment", b =>
                {
                    b.HasOne("NovaTech.TerraTech.Platform.ProfileManagement.Domain.Model.Aggregates.Profile", null)
                        .WithMany()
                        .HasForeignKey("AuthorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_comments__profile_author_profile_id");

                    b.HasOne("NovaTech.TerraTech.Platform.ProfileManagement.Domain.Model.Aggregates.Profile", null)
                        .WithMany()
                        .HasForeignKey("TargetProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_comments__profile_target_profile_id");
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.CommunityManagement.Domain.Model.Aggregates.CommunityProfile", b =>
                {
                    b.HasOne("NovaTech.TerraTech.Platform.ProfileManagement.Domain.Model.Aggregates.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_community_profiles__profile_profile_id");

                    b.OwnsOne("NovaTech.TerraTech.Platform.CommunityManagement.Domain.Model.ValueObjects.CommunityNickname", "Nickname", b1 =>
                        {
                            b1.Property<int>("CommunityProfileId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Nickname")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("nickname");

                            b1.HasKey("CommunityProfileId")
                                .HasName("p_k_community_profiles");

                            b1.ToTable("community_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CommunityProfileId")
                                .HasConstraintName("f_k_community_profiles_community_profiles_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.CommunityManagement.Domain.Model.ValueObjects.PublicBio", "PublicBio", b1 =>
                        {
                            b1.Property<int>("CommunityProfileId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Bio")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("public_bio");

                            b1.HasKey("CommunityProfileId")
                                .HasName("p_k_community_profiles");

                            b1.ToTable("community_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CommunityProfileId")
                                .HasConstraintName("f_k_community_profiles_community_profiles_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.CommunityManagement.Domain.Model.ValueObjects.Reputation", "ReputationScore", b1 =>
                        {
                            b1.Property<int>("CommunityProfileId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<int>("Score")
                                .HasColumnType("int")
                                .HasColumnName("reputation_score");

                            b1.HasKey("CommunityProfileId")
                                .HasName("p_k_community_profiles");

                            b1.ToTable("community_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CommunityProfileId")
                                .HasConstraintName("f_k_community_profiles_community_profiles_id");
                        });

                    b.Navigation("Nickname")
                        .IsRequired();

                    b.Navigation("PublicBio")
                        .IsRequired();

                    b.Navigation("ReputationScore")
                        .IsRequired();
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.OwnsOne("NovaTech.TerraTech.Platform.Iam.Domain.Model.ValueObjects.Email", "EmailAddress", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("email_address");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("i_x_users_email_address");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.Navigation("EmailAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.Aggregates.Device", b =>
                {
                    b.HasOne("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.Aggregates.SensorCatalogItem", null)
                        .WithMany()
                        .HasForeignKey("SensorCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_devices__sensor_catalog_item_sensor_code");

                    b.OwnsOne("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.ValueObjects.DeviceStatus", "Status", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("status");

                            b1.HasKey("Id")
                                .HasName("p_k_devices");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_devices_devices_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.ValueObjects.FieldId", "FieldId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("field_id");

                            b1.HasKey("Id")
                                .HasName("p_k_devices");

                            b1.HasIndex("Value")
                                .HasDatabaseName("i_x_devices_field_id");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_devices_devices_id");

                            b1.HasOne("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.Aggregates.Field", null)
                                .WithMany()
                                .HasForeignKey("Value")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("f_k_devices_fields_field_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.ValueObjects.LastSync", "LastSync", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("Value")
                                .HasColumnType("datetime")
                                .HasColumnName("last_sync");

                            b1.HasKey("Id")
                                .HasName("p_k_devices");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_devices_devices_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.ValueObjects.MacAddress", "MacAddress", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(17)
                                .HasColumnType("varchar(17)")
                                .HasColumnName("mac_address");

                            b1.HasKey("Id")
                                .HasName("p_k_devices");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("i_x_devices_mac_address");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_devices_devices_id");
                        });

                    b.Navigation("FieldId")
                        .IsRequired();

                    b.Navigation("LastSync")
                        .IsRequired();

                    b.Navigation("MacAddress")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.Aggregates.Field", b =>
                {
                    b.OwnsOne("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.ValueObjects.FieldName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_fields");

                            b1.ToTable("fields");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_fields_fields_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.ValueObjects.LocationLatLong", "LocationLatLong", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double")
                                .HasColumnName("longitude");

                            b1.HasKey("Id")
                                .HasName("p_k_fields");

                            b1.ToTable("fields");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_fields_fields_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.ValueObjects.ProfileId", "ProfileId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("profile_id");

                            b1.HasKey("Id")
                                .HasName("p_k_fields");

                            b1.HasIndex("Value")
                                .HasDatabaseName("i_x_fields_profile_id");

                            b1.ToTable("fields");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_fields_fields_id");

                            b1.HasOne("NovaTech.TerraTech.Platform.ProfileManagement.Domain.Model.Aggregates.Profile", null)
                                .WithMany()
                                .HasForeignKey("Value")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("f_k_fields__profile_profile_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.ValueObjects.SizeM2", "SizeM2", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<double>("Value")
                                .HasColumnType("double")
                                .HasColumnName("size_m2");

                            b1.HasKey("Id")
                                .HasName("p_k_fields");

                            b1.ToTable("fields");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_fields_fields_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.ValueObjects.SoilType", "SoilType", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("soil_type");

                            b1.HasKey("Id")
                                .HasName("p_k_fields");

                            b1.ToTable("fields");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_fields_fields_id");
                        });

                    b.Navigation("LocationLatLong")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("ProfileId")
                        .IsRequired();

                    b.Navigation("SizeM2")
                        .IsRequired();

                    b.Navigation("SoilType")
                        .IsRequired();
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.Aggregates.SensorReading", b =>
                {
                    b.HasOne("NovaTech.TerraTech.Platform.Monitoring.Domain.Model.Aggregates.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_sensor_readings_devices_device_id");
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.NotificationManagement.Domain.Model.Aggregates.Notification", b =>
                {
                    b.HasOne("NovaTech.TerraTech.Platform.ProfileManagement.Domain.Model.Aggregates.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_notifications__profile_profile_id");
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.ProfileManagement.Domain.Model.Aggregates.Profile", b =>
                {
                    b.HasOne("NovaTech.TerraTech.Platform.Iam.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_profiles_users_user_id");

                    b.OwnsOne("NovaTech.TerraTech.Platform.ProfileManagement.Domain.Model.ValueObjects.ContactPhone", "Phone", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("contact_phone");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.ProfileManagement.Domain.Model.ValueObjects.FundoName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("fundo_name");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.OwnsOne("NovaTech.TerraTech.Platform.ProfileManagement.Domain.Model.ValueObjects.ProfileThresholds", "Thresholds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<double>("Moisture")
                                .HasColumnType("double")
                                .HasColumnName("moisture_threshold");

                            b1.Property<double>("Temperature")
                                .HasColumnType("double")
                                .HasColumnName("temp_threshold");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("Thresholds")
                        .IsRequired();
                });

            modelBuilder.Entity("NovaTech.TerraTech.Platform.StockManagement.Domain.Model.Aggregates.Inventory", b =>
                {
                    b.HasOne("NovaTech.TerraTech.Platform.Iam.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_inventories_users_owner_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
